name: Go Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22", "1.23", "1.24", "1.25"]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run linter
        run: make fmt

      - name: Run vet
        run: make vet

      - name: Run tests
        run: make test TEST_FLAGS="-v"

      - name: Run tests with race detector
        run: make test TEST_FLAGS="-race -v"
